FROM node:22-alpine

RUN corepack enable
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

# Copy workspace configuration and lockfile
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./

# Copy package.json files for the service and its local dependencies
COPY apps/backend/package.json ./apps/backend/
COPY packages/shared/package.json ./packages/shared/

# Install dependencies
RUN --mount=type=cache,target=/pnpm/store \
    pnpm install

# We don't COPY the source code here because we will mount it as a volume
# in docker-compose.

EXPOSE 5001

CMD ["pnpm", "--filter", "backend", "dev"]
